Repository swellaby/rusty-hook, pull requests merged in 2019-07, with the labels that each got.

#53 feat: improve behavior when config file is missing
  .vscode/cSpell.json
  Cargo.lock
  Cargo.toml
  README.md
  src/config.rs
  src/git.rs
  src/git_test.rs
  src/hook_script.sh
  src/main.rs
  src/rusty_hook.rs
  src/rusty_hook_test.rs
Labels: enhancement

#55 Add cli upgrade/management support
  .azure-pipelines/build/pr.hook-scripts.yml
  .azure-pipelines/build/pr.linux.yml
  .azure-pipelines/build/pr.mac.yml
  .azure-pipelines/build/pr.windows.yml
  .vscode/cSpell.json
  Cargo.lock
  Cargo.toml
  src/git.rs
  src/git_test.rs
  src/hook_files/cli.sh
  src/hook_files/hook_script.sh
  src/hook_files/semver.sh
  src/hook_script.sh
  src/hooks.rs
  src/hooks_test.rs
  src/rusty_hook.rs
  tests/hook_files/cli.sh
  tests/hook_files/run_tests.sh
  tests/hook_files/semver.sh
  tests/hook_files/shunit2.sh
Labels: done, enhancement

#58 chore: add +x to git index for dev_setup.sh
  .azure-pipelines/build/pr.linux.yml
  scripts/dev_setup.sh
Labels: developer experience, done
